name: planmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.70.0
  firebase_storage: ^12.4.10
  mockito: ^5.5.0
  build_runner: ^2.6.0
  fake_cloud_firestore: ^3.1.0
  firebase_storage_mocks: ^0.7.0
  test: ^1.25.15
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.11.0
  lottie: ^3.3.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  animated_custom_dropdown: ^3.1.1
  cloud_functions: ^5.6.2
  material_symbols_icons: ^4.2873.0
  flutter_local_notifications: ^19.4.2
  firebase_messaging: ^15.2.10

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/newicons/
    - assets/avatar/
    - assets/lottie/

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
